FROM debian:bookworm

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y \
    vim \
    git \
    x11-common xserver-xorg \
    x11-apps \
    build-essential

COPY ./cheat.sh /home/

RUN chmod +x /home/cheat.sh
ENV DISPLAY=:0

ENTRYPOINT ["/home/cheat.sh"]
